apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-deployment
  labels:
    app: crm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crm
  template:
    metadata:
      labels:
        app: crm
    spec:
      containers:
        - name: crm-container
          image: haidertelusko/crm-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8484
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                envVarSource:
                  name: DB_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                envVarSource:
                  name: DB_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                envVarSource:
                  name: DB_PASS
